name: Checkout and restore dependencies
description: Checkout and restore dependencies
inputs:
    working-directory:
        description: Working directory
        required: false
        default: .
    additional-working-directory:
        description: Additional working directory
        required: false

# Sets common steps and ensure we use cached node_modules
runs:
    using: "composite"
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v5
          with:
            fetch-depth: 0

        - name: Use Node.js 24
          uses: actions/setup-node@v4
          with:
              node-version: 24

        - name: Cache dependencies npm
          id: check-dependencies-cache
          uses: actions/cache@v5
          with:
              path: ${{ inputs.working-directory }}/node_modules
              key: modules-npm-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}

        - name: Cache additional dependencies npm
          id: check-additional-dependencies-cache
          if: inputs.additional-working-directory != ''
          uses: actions/cache@v5
          with:
              path: ${{ inputs.additional-working-directory }}/node_modules
              key: modules-npm-${{ inputs.additional-working-directory }}-${{ hashFiles(format('{0}/package-lock.json', inputs.additional-working-directory)) }}

        - name: install npm dependencies
          if: steps.check-dependencies-cache.outputs.cache-hit != 'true'
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: npm ci

        - name: install additional npm dependencies
          if: inputs.additional-working-directory != '' && steps.check-additional-dependencies-cache.outputs.cache-hit != 'true'
          shell: bash
          working-directory: ${{ inputs.additional-working-directory }}
          run: npm ci

        # Repos can still have older version locally but on cloud we enforce uniformity.
        # This causes minor mismatch in package-lock.json and node_modules but it shouldn't cause any issues.
        - name: Enforce latest test tools version
          # We don't override beta so we can use it to test branch-specific versions of apify-test-tools
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          run: |
              locked_version=$(jq -r '.packages["node_modules/apify-test-tools"].version' package-lock.json)
              echo "Locked apify-test-tools version: $locked_version"
              if [[ "$locked_version" == *"-beta"* ]]; then
                echo "Beta version detected, reinstalling $locked_version to ensure cache consistency"
                npm install apify-test-tools@$locked_version --audit=false;
              else
                echo "Installing latest apify-test-tools"
                npm install apify-test-tools@latest --audit=false;
              fi
