name: Cache Dependencies

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                default: .
                required: false
            additional-working-directory:
                type: string
                required: false

jobs:
    cache-dependencies:
        name: Cache Dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            
            # A simple node script that converts secrets to env vars
            # Use specific commit SHA to prevent someone stealing that repo
            # - Useful for passing dynamic secrets to env variables, e.g. NPM_TOKEN to `npm ci` step
            - uses: oNaiPs/secrets-to-env-action@b64e0192bc4bd2ec0682dee8696470d4866577fa
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Cache dependencies npm
              id: check-dependencies-cache
              uses: actions/cache@v5
              with:
                  lookup-only: true
                  path: ${{ inputs.working-directory }}/node_modules
                  key: modules-npm-${{ inputs.working-directory }}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}

            - name: Cache additional dependencies npm
              id: check-additional-dependencies-cache
              if: inputs.additional-working-directory != ''
              uses: actions/cache@v5
              with:
                  lookup-only: true
                  path: ${{ inputs.additional-working-directory }}/node_modules
                  key: modules-npm-${{ inputs.additional-working-directory }}-${{ hashFiles(format('{0}/package-lock.json', inputs.additional-working-directory)) }}

            - name: install npm dependencies
              if: steps.check-dependencies-cache.outputs.cache-hit != 'true'
              run: |
                  cd ${{ inputs.working-directory }}
                  npm ci

            - name: install additional npm dependencies
              if: inputs.additional-working-directory != '' && steps.check-additional-dependencies-cache.outputs.cache-hit != 'true'
              run: |
                  cd ${{ inputs.additional-working-directory }}
                  npm ci
