name: Platform tests

on:
    workflow_call:
        inputs:
            subtest:
                type: string
                default: ""
                required: false

jobs:
    scheduledPlatformTests:
        name: Scheduled Platform tests
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: oNaiPs/secrets-to-env-action@b64e0192bc4bd2ec0682dee8696470d4866577fa
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Install dependencies
              run: npm install

            - name: Test
              run: |
                  set +e
                  export RUN_ALL_PLATFORM_TESTS=1
                  npx vitest ./test/platform/${{ inputs.subtest }} \
                    --run \
                    --reporter=default \
                    --reporter=json \
                    --outputFile=./test-output.json \
                    --maxConcurrency 20 \
                    --fileParallelism=true \
                    --maxWorkers 10
                  return_code=$?
                  npx apify-test-tools report-tests \
                    --report-file ./test-output.json \
                    --workflow-name "${{ github.workflow }}" \
                    --job-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                    --repository "${{ github.repository }}"
                  exit $return_code
