name: Platform tests

on:
    workflow_call:
        inputs:
            subtest:
                type: string
                default: ""
                required: false
            working-directory:
                type: string
                default: .
                required: false

jobs:
    scheduledPlatformTests:
        name: Scheduled Platform tests
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get github-actions-source ref
              id: gha_ref
              run: echo "ref=${GITHUB_WORKFLOW_REF##*@}" >> $GITHUB_OUTPUT

            - name: Checkout github-actions-source
              uses: actions/checkout@v4
              with:
                  repository: apify-store/github-actions-source
                  ref: ${{ steps.gha_ref.outputs.ref }}
                  path: .__gha-source__

            - uses: ./__gha-source__/.github/actions/setup-apify-test-tools
              with:
                  secrets: ${{ toJSON(secrets) }}
                  working-directory: ${{ inputs.working-directory }}

            - name: Test
              run: |
                  set +e
                  export RUN_ALL_PLATFORM_TESTS=1
                  npx vitest ./test/platform/${{ inputs.subtest }} \
                    --run \
                    --reporter=default \
                    --reporter=json \
                    --outputFile=./test-output.json \
                    --maxConcurrency 20 \
                    --fileParallelism=true \
                    --maxWorkers 100
                  return_code=$?
                  npx apify-test-tools report-tests \
                    --report-file ./test-output.json \
                    --workspace . \
                    --workflow-name "${{ github.workflow }}" \
                    --job-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
                    --report-slack-channel "#notif-${{ github.event.repository.name }}"
                  exit $return_code

            - name: Upload Vitest JSON artifact
              uses: actions/upload-artifact@v6
              if: always()
              with:
                  name: vitest-results
                  path: ./test-output.json