name: Test

on:
    workflow_call:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    platformTest:
        name: Build Devel and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            # We want platform tests but some repos that we migrate may not have unit tests or have only standalone-actors
            -   name: Check if we have tests folder
                run: |
                    if [ -d "code/test/platform" ]; then
                        echo "TEST_DIR=./code" >> $GITHUB_ENV
                    elif [ -d "test/platform" ]; then
                        echo "TEST_DIR=." >> $GITHUB_ENV
                    else
                        echo "Test folder not found at /test or /code/test. Skipping tests."
                        exit 0
                    fi

            - uses: oNaiPs/secrets-to-env-action@b64e0192bc4bd2ec0682dee8696470d4866577fa
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Cache base commit
              id: base_commit
              uses: actions/cache@v4
              with:
                path: ./base_commit.txt
                key: base_commit

            - name: Install dependencies
              run: npm install
              working-directory: ${{ env.TEST_DIR }}

            - name: Build
              id: build
              run: |
                  export base_commit=$(cat base_commit.txt)
                  actor_builds=$(npx apify-test-tools build --source-branch "origin/${{ github.head_ref }}" --target-branch "origin/${{ github.base_ref }}" $(test $base_commit && echo "--base-commit $base_commit" || echo ""))
                  echo "actor_builds=$actor_builds" | tee -a $GITHUB_OUTPUT
              working-directory: ${{ env.TEST_DIR }}

            - name: Test
              if: env.TEST_DIR != ''
              run: |
                  export ACTOR_BUILDS='${{ steps.build.outputs.actor_builds }}'
                  export RUN_PLATFORM_TESTS=1
                  npx vitest ./test/platform --run
              working-directory: ${{ env.TEST_DIR }}

            # NOTE: we want to cache the latest commit only if the tests are successfull
            - name: Cache latest commit
              run: |
                  export base_commit=$(cat base_commit.txt)
                  npx apify-test-tools get-latest-commit --source-branch "origin/${{ github.head_ref }}" --target-branch "origin/${{ github.base_ref }}" $(test $base_commit && echo "--base-commit $base_commit" || echo "") > ./base_commit.txt

    unitTest:
        # TODO: only run on changes to code
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            # We want unit tests but some repos that we migrate may not have unit tests or have only standalone-actors
            -   name: Check if we have tests folder
                run: |
                    if [ -d "code/test" ]; then
                        echo "TEST_DIR=./code" >> $GITHUB_ENV
                    elif [ -d "test" ]; then
                        echo "TEST_DIR=." >> $GITHUB_ENV
                    else
                        echo "Test folder not found at /test or /code/test. Skipping tests."
                        exit 0
                    fi
            -   name: Use Node.js 20
                uses: actions/setup-node@v3

                with:
                    node-version: 20
                    cache: 'npm'
                    cache-dependency-path: ${{ env.TEST_DIR }} # https://github.com/actions/setup-node/issues/706

            -   name: Install Dependencies
                run: npm ci
                working-directory: ${{ env.TEST_DIR }}

            -   name: TypeScript
                # Some repos require custom build checks, so we check if the `build-check` script exists and run it if 
                # it does. Otherwise default to the standard `npx tsc --noEmit` check
                run: |
                    HAS_CUSTOM_BUILD_CHECK=$(npx -y json -f package.json scripts.build-check)
                    if [ -z "$HAS_CUSTOM_BUILD_CHECK" ]; then
                        npx tsc --noEmit;
                    else
                        npm run build-check;
                    fi
                working-directory: ${{ env.TEST_DIR }}

            -   name: Lint
                run: npm run lint
                working-directory: ${{ env.TEST_DIR }}

            -   name: Test
                run: npm test
                working-directory: ${{ env.TEST_DIR }}
