name: PR -> Built devel and run tests
on:
    workflow_call:
        inputs:
            runnerLabel:
                description: 'prod or beta'
                type: string
                default: 'prod'
                
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    buildDevelAndTest:
        name: 'PR -> Build devel and test: ${{github.repository}} ${{github.event.head_commit.message}}'
        # TODO: Improve logic when to run stuff
        #if: |
        #  !contains(github.event.pull_request.message, '[skip ci]') &&
        #  !contains(github.event.head_commit.message, '[skip platform-test]')

        runs-on:
            labels: ${{inputs.runnerLabel}}
        steps:
            # We need to fetch at least 2 commits to make a diff for Changelog
            - uses: actions/checkout@v4
              with:
                fetch-depth: 2
            # A simple node script that converts secrets to env vars
            # Use specific commit SHA to prevent someone stealing that repo
            - uses: oNaiPs/secrets-to-env-action@b64e0192bc4bd2ec0682dee8696470d4866577fa
              with:
                secrets: ${{ toJSON(secrets) }}
            - name: Build and Test actor build
              run: npm run gha:start:build
