name: Build latest and report to slack

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                default: .
                required: false
            additional-working-directory:
                type: string
                required: false

jobs:
    pushBuildLatest:
        name: 'Build latest: ${{github.repository}} ${{github.event.head_commit.message}}'
        if: |
          !contains(github.event.head_commit.message, '[skip ci]') &&
          !contains(github.event.head_commit.message, '[skip platform-test]')

        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}

        steps:
            # A simple node script that converts secrets to env vars
            # Use specific commit SHA to protect from someone stealing that repo
            - uses: oNaiPs/secrets-to-env-action@b64e0192bc4bd2ec0682dee8696470d4866577fa
              with:
                secrets: ${{ toJSON(secrets) }}
    
            - name: Setup repository and dependencies
              uses: apify-store/github-actions-source/.github/actions/checkout-restore-dependencies@master
              with:
                  working-directory: ${{ inputs.working-directory }}
                  additional-working-directory: ${{ inputs.additional-working-directory }}

            - name: Release Actors and notify
              run: npx apify-test-tools release --push-event-path ${{ github.event_path }} --release-slack-channel "#delivery-public-actors" --report-slack-channel "#notif-${{ github.event.repository.name }}"

            - name: Delete old builds
              run: npx apify-test-tools delete-old-builds
