name: Build latest and report to slack

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                default: .
                required: false

jobs:
    pushBuildLatest:
        name: 'Build latest: ${{github.repository}} ${{github.event.head_commit.message}}'
        if: |
          !contains(github.event.head_commit.message, '[skip ci]') &&
          !contains(github.event.head_commit.message, '[skip platform-test]')

        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            # A simple node script that converts secrets to env vars
            # Use specific commit SHA to prevent someone stealing that repo
            - uses: oNaiPs/secrets-to-env-action@b64e0192bc4bd2ec0682dee8696470d4866577fa
              with:
                secrets: ${{ toJSON(secrets) }}

            - name: Use Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install apify-test-tools
              # We don't override beta so we can use it to test branch-specific versions of apify-test-tools
              # npm install still tries to respect repo package-lock.json so pulling new malware versions is very unlikely, we don't change dependencies in test-tools often
              run: |
                  TEST_TOOLS_VERSION=$(jq -r '(.dependencies // {}) + (.devDependencies // {}) | .["apify-test-tools"] // ""' package.json)
                  if echo "$TEST_TOOLS_VERSION" | grep -q "\-beta"; then
                    echo "Beta version ($TEST_TOOLS_VERSION) found in package.json, installing it"
                    npm install "apify-test-tools@$TEST_TOOLS_VERSION"
                  else
                    echo "No beta version in package.json, installing latest apify-test-tools"
                    npm install apify-test-tools@latest
                  fi

            - name: Build and Test actor build
              run: npx apify-test-tools release --push-event-path ${{ github.event_path }} --release-slack-channel "#delivery-public-actors" --report-slack-channel "#notif-${{ github.event.repository.name }}"

            - name: Delete old builds
              run: npx apify-test-tools delete-old-builds
