name: Build latest and report to slack

on:
    workflow_call:
        inputs:
            working-directory:
                type: string
                default: .
                required: false

jobs:
    pushBuildLatest:
        name: 'Build latest: ${{github.repository}} ${{github.event.head_commit.message}}'
        if: |
          !contains(github.event.head_commit.message, '[skip ci]') &&
          !contains(github.event.head_commit.message, '[skip platform-test]')

        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}

        steps:
            - uses: ./.github/actions/setup-apify-test-tools
              with:
                  secrets: ${{ toJSON(secrets) }}
                  working-directory: ${{ inputs.working-directory }}

            - name: Build and Test actor build
              run: npx apify-test-tools release --push-event-path ${{ github.event_path }} --release-slack-channel "#delivery-public-actors" --report-slack-channel "#notif-${{ github.event.repository.name }}"

            - name: Delete old builds
              run: npx apify-test-tools delete-old-builds
